general:
  artifacts:
    - "~/outputs"
machine:
  services:
    - docker

dependencies:
  cache_directories:
    - "~/docker"
    - "~/data"

  override:
    - if [[ ! -d ~/data/ds105 ]]; then wget -c -O ${HOME}/ds105.tar "https://drive.google.com/uc?export=download&confirm=sjgM&id=0B2JWN60ZLkgkVEpvQlpTWkJqRWM" && mkdir -p ${HOME}/data && tar xf ${HOME}/ds105.tar -C ${HOME}/data; fi
    - if [[ ! -d ~/data/ds105/derivatives/fmriprep ]]; then wget -c -O ${HOME}/Visual object recognition__1fa5c543-4438-47e0-8388-4afdc8f39e87__results.zip "https://openneuro.org/crn/jobs/59fb95271de31f0001f2037c/results/fileName?ticket=ticket" && mkdir -p ${HOME}/data/ds105/derivatives/fmriprep && unzip ${HOME}/Visual object recognition__1fa5c543-4438-47e0-8388-4afdc8f39e87__results.zip fmriprep/* -d ${HOME}/data/ds105/derivatives/fmriprep; fi
    - if [[ -e ~/docker/image.tar ]]; then docker load -i ~/docker/image.tar; fi
    - git describe --tags --always > version
    - docker build -t bids/${CIRCLE_PROJECT_REPONAME,,} . :
        timeout: 21600
    - mkdir -p ~/docker; docker save "bids/${CIRCLE_PROJECT_REPONAME,,}" > ~/docker/image.tar
    - mkdir -p ${HOME}/outputs

test:
  override:
    - docker run -ti --rm --read-only -v /tmp:/tmp -v /var/tmp:/var/tmp -v ${HOME}/data/ds105:/bids_dataset bids/${CIRCLE_PROJECT_REPONAME,,} --version
    - docker run -ti --rm --read-only -v /tmp:/tmp -v /var/tmp:/var/tmp -v ${HOME}/data/ds105:/bids_dataset -v ${HOME}/outputs:/outputs bids/${CIRCLE_PROJECT_REPONAME,,} /bids_dataset /outputs participant_prep -k objectviewing -p 1 2 :
        timeout: 21600
    - docker run -ti --rm --read-only -v /tmp:/tmp -v /var/tmp:/var/tmp -v ${HOME}/data/ds105:/bids_dataset -v ${HOME}/outputs:/outputs bids/${CIRCLE_PROJECT_REPONAME,,} /bids_dataset /outputs participant_test -k objectviewing -c face house -p 1 2 -d -z :
        timeout: 21600

deployment:
  hub:
    owner: BIDS-Apps
    tag: /.*/
    commands:
      - if [[ -n "$DOCKER_PASS" ]]; then docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS && docker push bids/${CIRCLE_PROJECT_REPONAME,,}:latest; fi :
          timeout: 21600
      - if [[ -n "$DOCKER_PASS" ]]; then docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS && docker tag bids/${CIRCLE_PROJECT_REPONAME,,} bids/${CIRCLE_PROJECT_REPONAME,,}:$CIRCLE_TAG && docker push bids/${CIRCLE_PROJECT_REPONAME,,}:$CIRCLE_TAG; fi :
          timeout: 21600
