version: 2
jobs:
  build:
    machine:
      image: circleci/classic:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - my_cache
      - run:
          name: Get Data and Extract
          command: |
            if [[ -d ~/data/ds105 ]]; then
              echo "Exists!"
              wget -c -O ${HOME}/ds105.tar "https://files.osf.io/v1/resources/653ew/providers/osfstorage/5b781237410f920018e5a4fc" && \
              mkdir -p ${HOME}/data && tar xf ${HOME}/ds105.tar -C ${HOME}/data;
            fi
      - run:
          command: |
            if [[ -e ~/docker/image.tar ]]; then
              echo DOCKER IMAGE EXISTS
              docker load -i ~/docker/image.tar;
            fi
            git describe --tags --always > version
            docker build -t bids/${CIRCLE_PROJECT_REPONAME,,}:latest .
            mkdir -p ~/docker
            docker save "bids/${CIRCLE_PROJECT_REPONAME,,}:latest" > ~/docker/image.tar
            mkdir -p ${HOME}/outputs
      - save_cache:
          key: my_cache
          paths:
            - "~/docker"
            - "~/data"
      - persist_to_workspace:
          root: ~/
          paths:
            - data/ds105
            - docker/image.tar
  test:
    machine:
      image: circleci/classic:latest
    steps:
      - attach_workspace:
          at: ~/data
      - run:
          command: |
            docker run -ti --rm --read-only -v /tmp:/tmp -v /var/tmp:/var/tmp -v ${HOME}/data/ds105:/bids_dataset bids/${CIRCLE_PROJECT_REPONAME,,} --version
            #docker run -ti --rm --read-only -v /tmp:/tmp -v /var/tmp:/var/tmp -v ${HOME}/data/ds105:/bids_dataset -v ${HOME}/outputs:/outputs bids/${CIRCLE_PROJECT_REPONAME,,} /bids_dataset /outputs participant_prep -k objectviewing -p 1 2
            #docker run -ti --rm --read-only -v /tmp:/tmp -v /var/tmp:/var/tmp -v ${HOME}/data/ds105:/bids_dataset -v ${HOME}/outputs:/outputs bids/${CIRCLE_PROJECT_REPONAME,,} /bids_dataset /outputs participant_test -k objectviewing -c face house -p 1 2 -d -z
  deploy:
    machine:
      image: circleci/classic:latest
    steps:
      #- attach_workspace:
      #    at: ~/docker
      - run: docker load -i ~/docker/image.tar
      - run:
          command: |
            if [[ -n "${DOCKER_PASS}" ]]; then
              docker login -u ${DOCKER_USER} -p ${DOCKER_PASS} && \
              docker push bids/${CIRCLE_PROJECT_REPONAME,,}:latest
              if [[ -n "${CIRCLE_TAG}" ]]; then
                docker tag bids/${CIRCLE_PROJECT_REPONAME,,} bids/${CIRCLE_PROJECT_REPONAME,,}:${CIRCLE_TAG}
                docker push bids/${CIRCLE_PROJECT_REPONAME,,}:${CIRCLE_TAG};
              fi
            fi
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
